all:
	python3 miniob_test.py \
        --test-case-dir=./test  \
        --test-case-scores=case-scores.json \
        --test-result-dir=result \
        --test-result-tmp-dir=./result_tmp \
        --use-unix-socket \
        --git-repo=https://github.com/wugouzi/miniob \
        --git-branch=wudengke \
        --code-type=git \
        --target-dir=./miniob \
        --log=stdout \
        --compile-make-args=-j8
